// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2CnDrI0pxKVQmNYziWCWtDtkWnLTnySM',
    appId: '1:422606762242:web:5f14c7aadf5e81b7e0921b',
    messagingSenderId: '422606762242',
    projectId: 'devs2blu-cf3e5',
    authDomain: 'devs2blu-cf3e5.firebaseapp.com',
    storageBucket: 'devs2blu-cf3e5.appspot.com',
    measurementId: 'G-9R19L7TFV3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuwfXSOggaAe8kCsybt27kSC647fKIWiY',
    appId: '1:422606762242:android:5f56af892e871067e0921b',
    messagingSenderId: '422606762242',
    projectId: 'devs2blu-cf3e5',
    storageBucket: 'devs2blu-cf3e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYeEXLqYkxznKb3f9BWghRq9Or2jV3xW4',
    appId: '1:422606762242:ios:64f460f8527413b1e0921b',
    messagingSenderId: '422606762242',
    projectId: 'devs2blu-cf3e5',
    storageBucket: 'devs2blu-cf3e5.appspot.com',
    iosBundleId: 'com.example.teste',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYeEXLqYkxznKb3f9BWghRq9Or2jV3xW4',
    appId: '1:422606762242:ios:0b1aed7b02033ebce0921b',
    messagingSenderId: '422606762242',
    projectId: 'devs2blu-cf3e5',
    storageBucket: 'devs2blu-cf3e5.appspot.com',
    iosBundleId: 'com.example.teste.RunnerTests',
  );
}
